--[[
gamemodes/breach/gamemode/classes.lua
--]]
CHAOSMODELS = {
"models/player/pmc_4/pmc__07.mdl",
}

MTFMODELS = {
"models/scp/soldier_2.mdl",
}

RESEARCHERMODELS = {
"models/scp/apsci_cohrt.mdl",
"models/scp/apsci_male_02.mdl",
"models/scp/apsci_male_03.mdl",
"models/scp/apsci_male_05.mdl",
"models/scp/apsci_male_07.mdl",
"models/scp/apsci_male_08.mdl",
"models/scp/apsci_male_09.mdl",
}

RESEARCHERMODELS2 = {
"models/player/kerry/class_scientist_5.mdl",
"models/player/kerry/class_scientist_7.mdl",
"models/player/kerry/class_scientist_2.mdl",
}

GUARDMODELS = {
"models/scp/guard_sci.mdl",
}

SECURITYMODELS = {
"models/scp/guard_noob.mdl",
}

CLASSDMODELS = {
"models/player/kerry/class_d_1.mdl",
"models/player/kerry/class_d_2.mdl",
"models/player/kerry/class_d_3.mdl",
"models/player/kerry/class_d_4.mdl",
"models/player/kerry/class_d_5.mdl",
"models/player/kerry/class_d_6.mdl",
"models/player/kerry/class_d_7.mdl",
}

SCP = {
"models/logone/player/035_player.mdl", -- SCP-035
"models/vinrax/player/scp049_player.mdl", -- SCP-049
"models/player/scp096.mdl", -- SCP-096
"models/scp/106/unity/unity_scp_106_player.mdl", -- SCP-106
"models/captainbigbutt/vocaloid/shadow_miku_append.mdl", -- SCP-001-KS
"models/breach173.mdl", -- SCP-173
"models/vinrax/scp294/scp294_lg.mdl", -- SCP-294
"models/vinrax/props/scp_513.mdl", -- SCP-513
"models/scp_682/scp_682.mdl", -- SCP-682
"models/scp/939/unity/unity_scp_939.mdl", -- SCP-939
"models/player/mishka/scp966.mdl", -- SCP-966
"models/scp/999/jq/scp_999_pmjq.mdl", -- SCP-999
"models/1048/tdy/tdybrownpm.mdl", -- SCP-1048
"models/1048/tdyear/tdybrownearpm.mdl", -- SCP-1048-A
"models/player/mrsilver/scp_066pm/scp_066_pm.mdl", -- SCP-066
"models/ninja/l4d2/clown/clown.mdl", -- SCP-993
"models/animals/raptor_npc.mdl", -- SCP-MR-REX
"models/abel/abel.mdl", -- SCP-076
"models/props/forest_monster/forest_monster2.mdl", -- SCP-860-2
"models/player/undead/undead.mdl", -- SCP-049-2
"models/mishka/models/scp420.mdl",
"models/Gibs/HGIBS.mdl",
"models/player/corpse1.mdl" -- SCP-457
}

ALLCLASSES = {
	scps = {
		name = "Объекты SCP",
		color = Color(116, 66, 200),
		roles = {
			{name = ROLES.ROLE_SCP035,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 3000,
			 armor = 0,
			 walkspeed = 0.6,
			 runspeed = 0.66,
			 jumppower = 0.83,
			 vest = nil,
			 models = SCP[1],
			 showmodel = SCP[1],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP066,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 1000,
			 armor = 0,
			 walkspeed = 1.04,
			 runspeed = 1.25,
			 jumppower = 0.83,
			 vest = nil,
			 models = SCP[15],
			 showmodel = SCP[15],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP049,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 3750,
			 armor = 0,
			 walkspeed = 0.58,
			 runspeed = 0.62,
			 jumppower = 0.83,
			 vest = nil,
			 models = SCP[2],
			 showmodel = SCP[2],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP0492,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 300,
			 armor = 0,
			 walkspeed = 0.71,
			 runspeed = 0.71,
			 jumppower = 0.75,
			 vest = nil,
			 models = SCP[20],
			 showmodel = SCP[20],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			--{name = ROLES.ROLE_SCP096,
			-- team = TEAM_SCP,
			-- weapons = {},
			-- showweapons = {},
			-- ammo = {},
			-- health = 2500,
			-- armor = 0,
			-- walkspeed = 0.83, --0.83
			-- runspeed = 1.46, --1.46
			-- jumppower = 0.83, --0.83
			-- vest = nil,
			-- models = SCP[3],
			-- showmodel = SCP[3],
			-- pmcolor = nil,
			-- flashlight = false,
			-- level = 0,
			-- max = 0,
			-- importancelevel = 1
			--},
			{name = ROLES.ROLE_SCP106,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 6500,
			 armor = 0,
			 walkspeed = 0.65,
			 runspeed = 0.68,
			 jumppower = 0.83,
			 vest = nil,
			 models = SCP[4],
			 showmodel = SCP[4],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP076,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 2800,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = {"models/abel/abel.mdl"},
			 showmodel = "models/abel/abel.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			--[[
			{name = ROLES.ROLE_SCP082,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 4500,
			 armor = 0,
			 walkspeed = 0.79,
			 runspeed = 1.66,
			 jumppower = 0.83,
			 vest = nil,
			 models = {"models/obese_male.mdl"},
			 showmodel = "models/obese_male.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			]]--
			--[[
			{name = ROLES.ROLE_SCP001KS,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 5000,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = {"models/captainbigbutt/vocaloid/shadow_miku_append.mdl"},
			 showmodel = "models/captainbigbutt/vocaloid/shadow_miku_append.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP002KS,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 2000,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = {"models/child.mdl"},
			 showmodel = "models/child.mdl",
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP003KS,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 3000,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = {"models/mailer/characters/tesv_greybeard.mdl"},
			 showmodel = "models/mailer/characters/tesv_greybeard.mdl",
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP004KS,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 4000,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = {"models/player/ravenwarriorplayer.mdl"},
			 showmodel = "models/player/ravenwarriorplayer.mdl",
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			]]--
			{name = ROLES.ROLE_SCP173,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 3250,
			 armor = 0,
			 walkspeed = 2.5,
			 runspeed = 2.5,
			 jumppower = 0.83,
			 vest = nil,
			 models = SCP[6],
			 showmodel = SCP[6],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP294,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {"Неигровой"},
			 ammo = {},
			 health = 0,
			 armor = 0,
			 walkspeed = 0,
			 runspeed = 0,
			 jumppower = 0,
			 vest = nil,
			 models = SCP[7],
			 showmodel = SCP[7],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP457,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 4000,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 0.79,
			 vest = nil,
			 models = SCP[23],
			 showmodel = SCP[23],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP513,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {"Неигровой"},
			 ammo = {},
			 health = 0,
			 armor = 0,
			 walkspeed = 0,
			 runspeed = 0,
			 jumppower = 0,
			 vest = nil,
			 models = SCP[8],
			 showmodel = SCP[8],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP682,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 4000,
			 armor = 0,
			 walkspeed = 0.79,
			 runspeed = 1.66,
			 jumppower = 0.83,
			 vest = nil,
			 models = SCP[9],
			 showmodel = SCP[9],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = "SCP-714",
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {"Неигровой", "Снимается командой !drop714 в чате"},
			 ammo = {},
			 health = 0,
			 armor = 0,
			 walkspeed = 0,
			 runspeed = 0,
			 jumppower = 0,
			 vest = nil,
			 models = {"models/mishka/models/scp714.mdl"},
			 showmodel = "models/mishka/models/scp714.mdl",
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP939,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 4000,
			 armor = 0,
			 walkspeed = 0.83,
			 runspeed = 1.46,
			 jumppower = 0.83,
			 vest = nil,
			 models = SCP[10],
			 showmodel = SCP[10],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP966,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 1500,
			 armor = 0,
			 walkspeed = 0.66,
			 runspeed = 0.71,
			 jumppower = 0.83,
			 vest = nil,
			 models = SCP[11],
			 showmodel = SCP[11],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			--{name = ROLES.ROLE_SCP993,
			-- team = TEAM_SCP,
			-- weapons = {},
			-- showweapons = {},
			-- ammo = {},
			-- health = 2000,
			-- armor = 0,
			-- walkspeed = 0.81,
			-- runspeed = 0.81,
			-- jumppower = 0.81,
			-- vest = nil,
			-- models = SCP[16],
			-- showmodel = SCP[16],
			-- pmcolor = nil,
			-- flashlight = false,
			-- level = 1,
			-- max = 0,
			-- importancelevel = 1
			--},
			{name = ROLES.ROLE_SCP999,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 2000,
			 armor = 0,
			 walkspeed = 0.71,
			 runspeed = 2.1,
			 jumppower = 0.83,
			 vest = nil,
			 models = SCP[12],
			 showmodel = SCP[12],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			--[[
			{name = ROLES.ROLE_SCP1000,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 3000,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 0.83,
			 vest = nil,
			 models = {"models/winningrook/gtav/bigfoot/bigfoot.mdl"},
			 showmodel = "models/winningrook/gtav/bigfoot/bigfoot.mdl",
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			]]--
			{name = ROLES.ROLE_SCP1048a,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 1500,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1.25,
			 jumppower = 0.83,
			 vest = nil,
			 models = SCP[14],
			 showmodel = SCP[14],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_SCP860,
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {},
			 ammo = {},
			 health = 3000,
			 armor = 0,
			 walkspeed = 0.77,
			 runspeed = 0.93,
			 jumppower = 1.04,
			 vest = nil,
			 models = SCP[19],
			 showmodel = SCP[19],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0,
			 importancelevel = 1
			},
			{name = "SCP-420-J",
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {"Неигровой"},
			 ammo = {},
			 health = 0,
			 armor = 0,
			 walkspeed = 0,
			 runspeed = 0,
			 jumppower = 0,
			 vest = nil,
			 models = SCP[21],
			 showmodel = SCP[21],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0
			},
			{name = "SCP-1123",
			 team = TEAM_SCP,
			 weapons = {},
			 showweapons = {"Неигровой"},
			 ammo = {},
			 health = 0,
			 armor = 0,
			 walkspeed = 0,
			 runspeed = 0,
			 jumppower = 0,
			 vest = nil,
			 models = SCP[22],
			 showmodel = SCP[22],
			 pmcolor = nil,
			 flashlight = false,
			 level = 0,
			 max = 0
			},
		}
	},
	classds = {
		name = "Расходный Персонал",
		color = Color(255, 130, 0),
		roles = {
			{name = ROLES.ROLE_CLASSD,
			 team = TEAM_CLASSD,
			 weapons = {"br_holster", "br_id"},
			 showweapons = {},
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = CLASSDMODELS,
			 showmodel = nil,
			 level = 0,
			 customcheck = nil,
			 flashlight = false,
			 max = 64
			},
			{name = ROLES.ROLE_VETERAN,
			 team = TEAM_CLASSD,
			 weapons = {"br_holster", "br_id"},
			 showweapons = {},
			 ammo = {},
			 health = 150,
			 armor = 0,
			 walkspeed = 1.2,
			 runspeed = 1.2,
			 jumppower = 1.2,
			 vest = nil,
			 models = CLASSDMODELS,
			 showmodel = nil,
			 flashlight = false,
			 level = 6,
			 max = 4,
			 importancelevel = 6
			},
			{name = ROLES.ROLE_CLASSD_THIEF,
			 team = TEAM_CLASSD,
			 weapons = {"br_holster", "br_id", "keycard_level3"},
			 showweapons = {"Карта доступа 3 уровень"},
			 ammo = {},
			 health = 125,
			 armor = 0,
			 walkspeed = 1.1,
			 runspeed = 1.1,
			 jumppower = 1.1,
			 vest = nil,
			 models = CLASSDMODELS,
			 showmodel = nil,
			 flashlight = true,
			 level = 4,
			 max = 2,
			 importancelevel = 4
			},
			{name = ROLES.ROLE_CLASSD_KILLER,
			 team = TEAM_CLASSD,
			 weapons = {"br_holster", "br_id", "m9k_m92beretta"},
			 showweapons = {"M92 Beretta"},
			 ammo = {{"Pistol", 20}},
			 health = 150,
			 armor = 0,
			 walkspeed = 1.1,
			 runspeed = 1.1,
			 jumppower = 1.1,
			 vest = nil,
			 models = CLASSDMODELS,
			 showmodel = nil,
			 flashlight = false,
			 level = 7,
			 max = 1,
			 importancelevel = 7
			}
		}
	},
	researchers = {
		name = "Научный Персонал",
		color = Color(66, 188, 244),
		roles = {
			{name = ROLES.ROLE_RES,
			 team = TEAM_SCI,
			 weapons = {"br_holster", "br_id", "keycard_level2", "item_medkit"},
			 showweapons = {"Карта доступа 2 уровень", "Аптечка"},
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = RESEARCHERMODELS,
			 showmodel = nil,
			 flashlight = true,
			 level = 1,
			 max = 36,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_MEDIC,
			 team = TEAM_SCI,
			 weapons = {"br_holster", "br_id", "keycard_level2", "item_ultramedkit"},
			 showweapons = {"Карта доступа 2 уровень", "Большая аптечка"},
			 ammo = {},
			 health = 100,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = {"models/scp/pmedic01.mdl"},
			 showmodel = nil,
			 flashlight = true,
			 level = 2,
			 max = 18,
			 importancelevel = 2
			},
		 {name = ROLES.ROLE_RES_GEARS,
			team = TEAM_SCI,
			weapons = {"br_holster", "br_id", "keycard_level3", "item_ultramedkit"},
			showweapons = {"Карта доступа 3 уровень", "Большая аптечка"},
			ammo = {},
			health = 120,
			armor = 0,
			walkspeed = 1,
			runspeed = 1,
			jumppower = 1,
			vest = nil,
			models = {"models/scp/apsci_male_09.mdl"},
			showmodel = nil,
			flashlight = true,
			level = 9,
			max = 1,
			importancelevel = 9
		},
		{name = ROLES.ROLE_RES_LI,
		 team = TEAM_SCI,
		 weapons = {"br_holster", "br_id", "keycard_level3", "item_ultramedkit"},
		 showweapons = {"Карта доступа 3 уровень", "Большая аптечка"},
		 ammo = {},
		 health = 120,
		 armor = 0,
		 walkspeed = 1,
		 runspeed = 1,
		 jumppower = 1,
		 vest = nil,
		 models = {"models/scp/apsci_male_05.mdl"},
		 showmodel = nil,
		 flashlight = true,
		 level = 8,
		 max = 1,
		importancelevel = 8
	  },
		{name = ROLES.ROLE_RES_MING,
		 team = TEAM_SCI,
		 weapons = {"br_holster", "br_id", "keycard_level3", "item_ultramedkit"},
		 showweapons = {"Карта доступа 3 уровень", "Большая аптечка"},
		 ammo = {},
		 health = 120,
		 armor = 0,
		 walkspeed = 1,
		 runspeed = 1,
		 jumppower = 1,
		 vest = nil,
		 models = {"models/scp/apsci_cohrt.mdl"},
		 showmodel = nil,
		 flashlight = true,
		 level = 7,
		 max = 1,
		importancelevel = 7
	  },
		{name = ROLES.ROLE_RES_FERGUS,
		 team = TEAM_SCI,
		 weapons = {"br_holster", "br_id", "keycard_level3", "item_ultramedkit"},
		 showweapons = {"Карта доступа 3 уровень", "Большая аптечка"},
		 ammo = {},
		 health = 120,
		 armor = 0,
		 walkspeed = 1,
		 runspeed = 1,
		 jumppower = 1,
		 vest = nil,
		 models = {"models/scp/apsci_male_07.mdl"},
		 showmodel = nil,
		 flashlight = true,
		 level = 10,
		 max = 1,
		 importancelevel = 10
	  },
		{name = ROLES.ROLE_RES_MAYNARD,
		 team = TEAM_SCI,
		 weapons = {"br_holster", "br_id", "keycard_level4", "item_ultramedkit", "m9k_usp"},
		 showweapons = {"Карта доступа 4 уровень", "Большая аптечка", "USP"},
		 ammo = {{"Pistol", 30}},
		 health = 120,
		 armor = 0,
		 walkspeed = 1,
		 runspeed = 1,
		 jumppower = 1,
		 vest = nil,
		 models = {"models/scp/apsci_male_02.mdl"},
		 showmodel = nil,
		 flashlight = true,
		 level = 15,
		 max = 1,
		 importancelevel = 15
	  },
		}
	},
	security = {
		name = "Служебный Персонал",
		color = Color(0, 100, 255),
		roles = {
			{name = ROLES.ROLE_SECURITY,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level2", "item_radio", "breach_stunstick", "m9k_magpulpdr", "m9k_usp"},
			 showweapons = {"Карта доступа 2 уровень", "Рация", "Дубинка", "Magpul PDR", "USP"},
			 ammo = {{"SMG1", 300}, {"Pistol", 35}},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.9,
			 runspeed = 0.95,
			 jumppower = 0.9,
			 vest = "armor_security",
			 models = SECURITYMODELS,
			 showmodel = SECURITYMODELS[1],
			 pmcolor = nil,
			 flashlight = true,
			 level = 1,
			 max = 24,
			 sorting = 0,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_CSECURITY,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level4", "item_radio", "breach_stunstick", "m9k_smgp90", "m9k_usp"},
			 showweapons = {"Карта доступа 4 уровень", "Рация", "Дубинка", "P90", "USP"},
			 ammo = {{"SMG1", 300}, {"Pistol", 35}},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.9,
			 runspeed = 0.95,
			 jumppower = 0.9,
			 vest = "armor_security",
			 models = SECURITYMODELS,
			 showmodel = "models/player/kerry/class_securety.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 5,
			 max = 2,
			 sorting = 6,
			 importancelevel = 2
			},
			{name = ROLES.ROLE_MTFGUARD,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level3", "item_radio", "breach_stunstick", "m9k_m416", "m9k_usp"},
			 showweapons = {"Карта доступа 3 уровень", "Рация", "Дубинка", "HK 416", "USP"},
			 ammo = {{"AR2", 300}, {"Pistol", 35}},
			 health = 110,
			 armor = 0,
			 walkspeed = 0.85,
			 runspeed = 0.92,
			 jumppower = 0.87,
			 vest = "armor_mtfguard",
			 models = SECURITYMODELS,
			 showmodel = GUARDMODELS[1],
			 pmcolor = nil,
			 flashlight = true,
			 level = 1,
			 max = 12,
			 sorting = 1,
			 importancelevel = 1
			},
			--[[{name = ROLES.ROLE_CHAOSSPY,
			 team = TEAM_CHAOS,
			 weapons = {"br_holster", "br_id", "keycard_level3", "item_radio", "breach_stunstick", "m9k_m416"},
			 showweapons = {"Карта доступа 3 уровень", "Рация", "Дубинка", "UMP"},
			 ammo = {{"SMG1", 200}},
			 health = 100,
			 armor = 0,
			 walkspeed = 0.85,
			 runspeed = 0.92,
			 jumppower = 0.87,
			 vest = "armor_mtfguard",
			 models = SECURITYMODELS,
			 showmodel = "models/mtf/mtf remasteredhd.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 3,
			 max = 2,
			 sorting = 2,
			 importancelevel = 1
			},]]--
			{name = ROLES.ROLE_MTFMEDIC,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level3", "item_radio", "item_ultramedkit", "breach_stunstick", "m9k_m416"},
			 showweapons = {"Карта доступа 3 уровень", "Рация", "Большая аптечка", "Дубинка", "HK 416"},
			 ammo = {{"AR2", 300}},
			 health = 125,
			 armor = 0,
			 walkspeed = 0.85,
			 runspeed = 0.92,
			 jumppower = 0.87,
			 vest = "armor_mtfmedic",
			 models = SECURITYMODELS,
			 showmodel = "models/scp/guard_med.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 5,
			 max = 3,
			 sorting = 3,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_MTFL,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level4", "item_radio", "item_nvg", "breach_stunstick", "m9k_f2000"},
			 showweapons = {"Карта доступа 4 уровень", "Рация", "ПНВ", "Дубинка", "F2000"},
			 ammo = {{"SMG1", 300}},
			 health = 150,
			 armor = 0,
			 walkspeed = 0.87,
			 runspeed = 0.94,
			 jumppower = 0.9,
			 vest = "armor_mtfl",
			 models = SECURITYMODELS,
			 showmodel = "models/scp/guard_left.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 4,
			 max = 6,
			 sorting = 4,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_HAZMAT,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level4", "item_radio", "item_nvg", "breach_stunstick", "m9k_m249lmg"},
			 showweapons = {"Карта доступа 4 уровень", "Рация", "ПНВ", "Дубинка", "M249"},
			 ammo = {{"AR2", 500}},
			 health = 175,
			 armor = 50,
			 walkspeed = 0.93,
			 runspeed = 0.98,
			 jumppower = 0.92,
			 vest = "armor_hazmat",
			 models = SECURITYMODELS,
			 showmodel = "models/scp/soldier_4.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 8,
			 max = 3,
			 sorting = 5,
			 importancelevel = 1
			},
			{name = ROLES.ROLE_MTFCOM,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level5", "item_radio", "item_nvg", "breach_stunstick", "m9k_magpulpdr"},
			 showweapons = {"Карта доступа 5 уровень", "Рация", "ПНВ", "Дубинка", "Magpul PDR"},
			 ammo = {{"SMG1", 300}},
			 health = 150,
			 armor = 0,
			 walkspeed = 0.9,
			 runspeed = 0.94,
			 jumppower = 0.9,
			 vest = "armor_mtfcom",
			 models = SECURITYMODELS,
			 showmodel = "models/scp/captain.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 7,
			 max = 3,
			 sorting = 7,
			 importancelevel = 3
			},
			{name = ROLES.ROLE_SD,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_omni", "item_radio", "breach_stunstick", "m9k_coltpython"},
			 showweapons = {"Карта доступа Омни", "ПНВ", "Дубинка", "Colt Python"},
			 ammo = {{"357", 300}},
			 health = 125,
			 armor = 0,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 vest = nil,
			 models = {"models/armacham/scientists/scientists_8.mdl"},
			 showmodel = "models/armacham/scientists/scientists_8.mdl",
			 pmcolor = Color(0,0,0),
			 flashlight = true,
			 level = 12,
			 max = 1,
			 sorting = 8,
			 importancelevel = 4
			},
			{name = ROLES.ROLE_HSSPY,
			 team = TEAM_SPYHSS,
			 weapons = {"br_holster", "br_id", "br_id_hs", "keycard_level3", "item_radio", "breach_stunstick", "m9k_m416", "m9k_usp"},
			 showweapons = {"Карта доступа 3 уровень", "Рация", "Дубинка", "HK 416", "USP"},
			 ammo = {{"AR2", 300}, {"Pistol", 35}},
			 health = 110,
			 armor = 0,
			 walkspeed = 0.85,
			 runspeed = 0.92,
			 jumppower = 0.87,
			 vest = "armor_mtfguard",
			 models = SECURITYMODELS,
			 showmodel = GUARDMODELS[1],
			 pmcolor = nil,
			 flashlight = true,
			 level = 1,
			 max = 1,
			 sorting = 2,
			 importancelevel = 1
			},
		}
	},

	support = {
		name = "Полевой Персонал",
		color = Color(29, 81, 56),
		roles = {
			{name = ROLES.ROLE_MTFNTF,
			 team = TEAM_GUARD,
			 weapons = {"br_holster", "br_id", "keycard_level5", "item_radio", "item_nvg", "breach_stunstick", "m9k_famas", "m9k_glock", "item_ultramedkit"},
			 showweapons = {"Карта доступа 5 уровень", "Рация", "ПНВ", "Дубинка", "FAMAS", "Glock 18"},
			 ammo = {{"AR2", 300}, {"Pistol", 75}},
			 health = 200,
			 armor = 25,
			 walkspeed = 0.86,
			 runspeed = 0.93,
			 jumppower = 0.85,
			 vest = "armor_ntf",
			 models = SECURITYMODELS,
			 showmodel = MTFMODELS[1],
			 pmcolor = nil,
			 flashlight = true,
			 level = 3,
			 max = 6
			},
			{name = ROLES.ROLE_CHAOS,
			 team = TEAM_CHAOS,
			 weapons = {"br_holster", "br_id", "keycard_level4", "item_radio", "breach_stunstick", "m9k_ak47", "m9k_colt1911", "item_ultramedkit"},
			 showweapons = {"Карта доступа 4 уровень", "Рация", "Дубинка", "AK-47", "Colt 1911"},
			 ammo = {{"AR2", 300}, {"Pistol", 50}},
			 health = 200,
			 armor = 25,
			 walkspeed = 0.86,
			 runspeed = 0.93,
			 jumppower = 0.85,
			 vest = "armor_chaosins",
			 models = SECURITYMODELS,
			 showmodel = CHAOSMODELS[1],
			 pmcolor = nil,
			 flashlight = true,
			 level = 4,
			 max = 6
			},
			--[[
			{name = ROLES.ROLE_GOK,
			 team = TEAM_GOK,
			 weapons = {"br_holster", "br_id", "keycard_level5", "item_radio", "breach_stunstick", "m9k_acr", "m9k_sig_p229r", "item_ultramedkit", "item_nvg"},
			 showweapons = {"Карта доступа 5 уровень", "Рация", "Дубинка", "ACR", "SIG Sauer P229R", "ПНВ"},
			 ammo = {{"AR2", 300}, {"Pistol", 50}},
			 health = 220,
			 armor = 50,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 models = {"models/mark2580/payday2/pd2_swat_heavy_zeal_player.mdl"},
			 showmodel = "models/mark2580/payday2/pd2_swat_heavy_zeal_player.mdl", --"models/player/tfa_kz_helghast_assault.mdl"
			 pmcolor = nil,
			 flashlight = true,
			 level = 6,
			 max = 6
			},
			{name = ROLES.ROLE_SNEAK,
			 team = TEAM_SNEAK,
			 weapons = {"br_holster", "br_id", "keycard_level4", "item_radio", "breach_stunstick", "m9k_ak74", "m9k_hk45", "item_ultramedkit", "item_nvg"},
			 showweapons = {"Карта доступа 4 уровень", "Рация", "Дубинка", "AK-74", "HK45C", "ПНВ"},
			 ammo = {{"AR2", 300}, {"Pistol", 50}},
			 health = 200,
			 armor = 50,
			 walkspeed = 1,
			 runspeed = 1,
			 jumppower = 1,
			 models = {"models/player/r6s_mute.mdl"},
			 showmodel = "models/player/r6s_mute.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 5,
			 max = 6
			},
			{name = ROLES.ROLE_PSIXON,
			 team = TEAM_PSIXON,
			 weapons = {"br_holster", "br_id", "keycard_level4", "item_radio", "breach_stunstick", "m9k_scar", "m9k_m29satan", "item_ultramedkit", "item_nvg"},
			 showweapons = {"Карта доступа 4 уровень", "Рация", "Дубинка", "SCAR", "M29 Satan", "ПНВ", "Детектор движений"},
			 ammo = {{"AR2", 300}, {"Pistol", 50}, {"357", 24}, {"RPG_Round", 3}},
			 health = 300,
			 armor = 90,
			 walkspeed = 1.15,
			 runspeed = 1.15,
			 jumppower = 1.25,
			 models = {"models/player/tfa_kz_helghast_assault.mdl"},
			 showmodel = "models/player/tfa_kz_helghast_assault.mdl",
			 pmcolor = nil,
			 flashlight = true,
			 level = 35,
			 max = 5
			},
			]]--
		}
	}
}


