--[[
lua/autorun/fastdl.lua
--]]
if SERVER then
	resource.AddFile("sound/lowhpsound/heartbeat.wav")
	
	resource.AddFile("sound/music/music1.wav")
	resource.AddFile("sound/music/music2.wav")
	resource.AddFile("sound/music/music3.wav")
	resource.AddFile("sound/music/music4.wav")
	
	resource.AddFile("sound/music/scpcha.wav")
	
	resource.AddFile("sound/round_mk/end1.wav")
	resource.AddFile("sound/round_mk/end2.wav")
	resource.AddFile("sound/round_mk/end3.wav")
	resource.AddFile("sound/round_mk/end4.wav")
	
	resource.AddFile( "sound/navexradsounds/psi/targeton/TD_01.wav" )
	resource.AddFile( "sound/navexradsounds/psi/targeton/TD_02.wav" )
	resource.AddFile( "sound/navexradsounds/psi/targeton/TD_03.wav" )
	resource.AddFile( "sound/navexradsounds/psi/targeton/TD_04.wav" )
	resource.AddFile( "sound/navexradsounds/psi/targeton/TD_05.wav" )
	resource.AddFile( "sound/navexradsounds/psi/targetoff/TLD_01.wav" )
	resource.AddFile( "sound/navexradsounds/psi/targetoff/TLD_02.wav" )
	resource.AddFile( "sound/navexradsounds/psi/targetoff/TLD_03.wav" )
	resource.AddFile( "sound/navexradsounds/psi/targetoff/TLD_04.wav" )
	resource.AddFile( "sound/navexradsounds/psi/stop/Stop_01.wav" )
	resource.AddFile( "sound/navexradsounds/psi/stop/Stop_02.wav" )
	resource.AddFile( "sound/navexradsounds/psi/stop/Stop_03.wav" )
	resource.AddFile( "sound/navexradsounds/psi/stop/Stop_04.wav" )
	resource.AddFile( "sound/navexradsounds/psi/stop/Stop_05.wav" )
	resource.AddFile( "sound/navexradsounds/psi/random/RandomPS_01.wav" )
	resource.AddFile( "sound/navexradsounds/psi/random/RandomPS_02.wav" )
	resource.AddFile( "sound/navexradsounds/psi/random/RandomPS_03.wav" )
	resource.AddFile( "sound/navexradsounds/psi/random/RandomPS_04.wav" )
	resource.AddFile( "sound/navexradsounds/psi/poisk/SearchG_01.wav" )
	resource.AddFile( "sound/navexradsounds/psi/poisk/SearchG_02.wav" )
	resource.AddFile( "sound/navexradsounds/psi/poisk/SearchG_03.wav" )
	resource.AddFile( "sound/navexradsounds/psi/poisk/SearchG_04.wav" )
	resource.AddFile( "sound/navexradsounds/psi/id/ID_01.wav" )
	resource.AddFile( "sound/navexradsounds/psi/id/ID_02.wav" )
	resource.AddFile( "sound/navexradsounds/psi/id/ID_03.wav" )
	
	resource.AddFile( "sound/navexradsounds/mtf/targetoff/TL_01.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/targetoff/TL_02.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/targetoff/TL_03.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/targetoff/TL_04.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/stop/Stop_01.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/stop/Stop_02.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/stop/Stop_03.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/stop/Stop_04.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/stop/Stop_05.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/random/Random_01.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/random/Random_02.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/random/Random_03.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/random/Random_04.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/random/Random_05.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/poisk/Search_01.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/poisk/Search_02.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/poisk/Search_03.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/poisk/Search_04.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/id/ID_01.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/id/ID_02.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/id/ID_03.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/classdd/DD_01.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/classdd/DD_02.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/classdd/DD_03.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/classdd/DD_04.wav" )
	resource.AddFile( "sound/navexradsounds/mtf/classdd/DD_05.wav" )
	
	resource.AddFile( "sound/navexradsounds/hs/targeton/TD_01.wav" )
	resource.AddFile( "sound/navexradsounds/hs/targeton/TD_02.wav" )
	resource.AddFile( "sound/navexradsounds/hs/targeton/TD_03.wav" )
	resource.AddFile( "sound/navexradsounds/hs/targeton/TD_04.wav" )
	resource.AddFile( "sound/navexradsounds/hs/targeton/TD_05.wav" )
	resource.AddFile( "sound/navexradsounds/hs/targetoff/TLD_01.wav" )
	resource.AddFile( "sound/navexradsounds/hs/targetoff/TLD_02.wav" )
	resource.AddFile( "sound/navexradsounds/hs/targetoff/TLD_03.wav" )
	resource.AddFile( "sound/navexradsounds/hs/targetoff/TLD_04.wav" )
	resource.AddFile( "sound/navexradsounds/hs/stop/Stop_01.wav" )
	resource.AddFile( "sound/navexradsounds/hs/stop/Stop_02.wav" )
	resource.AddFile( "sound/navexradsounds/hs/stop/Stop_03.wav" )
	resource.AddFile( "sound/navexradsounds/hs/stop/Stop_04.wav" )
	resource.AddFile( "sound/navexradsounds/hs/stop/Stop_05.wav" )
	resource.AddFile( "sound/navexradsounds/hs/random/RandomD_01.wav" )
	resource.AddFile( "sound/navexradsounds/hs/random/RandomD_02.wav" )
	resource.AddFile( "sound/navexradsounds/hs/random/RandomD_03.wav" )
	resource.AddFile( "sound/navexradsounds/hs/random/RandomD_04.wav" )
	resource.AddFile( "sound/navexradsounds/hs/poisk/SearchD_01.wav" )
	resource.AddFile( "sound/navexradsounds/hs/poisk/SearchD_02.wav" )
	resource.AddFile( "sound/navexradsounds/hs/poisk/SearchD_03.wav" )
	resource.AddFile( "sound/navexradsounds/hs/poisk/SearchD_04.wav" )
	resource.AddFile( "sound/navexradsounds/hs/id/ID_01.wav" )
	resource.AddFile( "sound/navexradsounds/hs/id/ID_02.wav" )
	resource.AddFile( "sound/navexradsounds/hs/id/ID_03.wav" )
	
	resource.AddFile( "sound/navexradsounds/gok/targeton/TD_01.wav" )
	resource.AddFile( "sound/navexradsounds/gok/targeton/TD_02.wav" )
	resource.AddFile( "sound/navexradsounds/gok/targeton/TD_03.wav" )
	resource.AddFile( "sound/navexradsounds/gok/targeton/TD_04.wav" )
	resource.AddFile( "sound/navexradsounds/gok/targeton/TD_05.wav" )
	resource.AddFile( "sound/navexradsounds/gok/targetoff/TLD_01.wav" )
	resource.AddFile( "sound/navexradsounds/gok/targetoff/TLD_02.wav" )
	resource.AddFile( "sound/navexradsounds/gok/targetoff/TLD_03.wav" )
	resource.AddFile( "sound/navexradsounds/gok/targetoff/TLD_04.wav" )
	resource.AddFile( "sound/navexradsounds/gok/stop/Stop_01.wav" )
	resource.AddFile( "sound/navexradsounds/gok/stop/Stop_02.wav" )
	resource.AddFile( "sound/navexradsounds/gok/stop/Stop_03.wav" )
	resource.AddFile( "sound/navexradsounds/gok/stop/Stop_04.wav" )
	resource.AddFile( "sound/navexradsounds/gok/stop/Stop_05.wav" )
	resource.AddFile( "sound/navexradsounds/gok/random/RandomG_01.wav" )
	resource.AddFile( "sound/navexradsounds/gok/random/RandomG_02.wav" )
	resource.AddFile( "sound/navexradsounds/gok/random/RandomG_03.wav" )
	resource.AddFile( "sound/navexradsounds/gok/random/RandomG_04.wav" )
	resource.AddFile( "sound/navexradsounds/gok/poisk/SearchG_01.wav" )
	resource.AddFile( "sound/navexradsounds/gok/poisk/SearchG_02.wav" )
	resource.AddFile( "sound/navexradsounds/gok/poisk/SearchG_03.wav" )
	resource.AddFile( "sound/navexradsounds/gok/poisk/SearchG_04.wav" )
	resource.AddFile( "sound/navexradsounds/gok/id/ID_01.wav" )
	resource.AddFile( "sound/navexradsounds/gok/id/ID_02.wav" )
	resource.AddFile( "sound/navexradsounds/gok/id/ID_03.wav" )
	
	resource.AddFile( "sound/navexradsounds/anons/Ann_01.wav" )
	resource.AddFile( "sound/navexradsounds/anons/Ann_02.wav" )
	resource.AddFile( "sound/navexradsounds/anons/Ann_03.wav" )
	resource.AddFile( "sound/navexradsounds/anons/Ann_04.wav" )
	
	resource.AddFile( "materials/talkicon/text.png" )
	resource.AddFile( "materials/talkicon/voice.png" )
	


end

